### ISSUE TITLE
Cloud Code?

### ISSUE THREAD

**Issue by binarytide** [Exeteres/vue-parse#1]
Any plans to add a cloud code trigger?

**Comment by Exeteres** [comment]
You mean getting data from cloud functions? 
Something like that:
```js
parse: {
    averageStars: {
        function: "averageStars",
        params() {
            return {
                movie: this.movie
            }
        }
    }
}
```

**Comment by binarytide** [comment]
yes, possibly with the ability to call within component methods as well via this.$parse.Cloud (or something similar)

**Comment by Exeteres** [comment]
Ok, I'll think about it
However, what you are talking about is just an alias to Parse.Cloud methods, isn't it?

**Comment by binarytide** [comment]
correct, wasn't sure if you could continue to call the same way or if you wanted to integrate. knowing I can easily call it is good enough for me

**Comment by Exeteres** [comment]
For that matter, I plan to add a wrapper for the original Parse SDK to make it even neater.
However, I will not get involved much, I will try to do it as soon as possible.

**Comment by binarytide** [comment]
that would be perfect, that way user would in theory only need your lib and documentation to get started on the client side.

**Comment by Exeteres** [comment]
At the moment I added aliases for all 4 methods from Parse.Cloud and updated the documentation.
https://exeteres.github.io/vue-parse/guide/usage/parse-sdk.html
I only tested the 'run' method, please check the remaining ones if you need them.
I will also continue to add aliases for other methods and at the same time implement the declarative way to use cloud code.

**Comment by Exeteres** [comment]
Also implemented a declarative way to use cloud code.
Please close the issue if you no longer have questions, problems or suggestions regarding cloud code.
https://exeteres.github.io/vue-parse/guide/usage/cloud-functions.html
