### ISSUE TITLE
Cloud function support not published on NPM

### ISSUE THREAD

**Issue by daluege** [Exeteres/vue-parse#6]
Hey,
congratulations for your well-designed package. The support of cloud functions currently appears in the documentation (gh-pages) but is not yet available in the NPM 0.1.0 version, which was quite confusing to me. Would you mind fixing that?
Kind regards

**Comment by Exeteres** [comment]
It seems that I just forgot to upload this. I uploaded it as 0.2.0 now.
Please note that this project was created about a year ago and may be outdated.
I managed to update some dependencies, but all versions of parse-sdk, starting from 2.5.1, break something. So i froze the latest supported version in the package.json.
I hope that is not critical for you.
Anyway now I have no time to maintain this project, sorry.

**Comment by daluege** [comment]
Thank you very much :)
It is a well-designed package from my point of view and has been 100% stable for the development of a small app. Thanks
